### ANUNCIOS

### GET exchanges
GET http://localhost:8000/exchanges
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MjEwNzMsImV4cCI6MTcyMjgyNDY3M30.ArabQ7sMsSm5326TW8i4RZb7mJ9BxkPrqAgBAeXnqrQ

###

### GET exchanges/:id
GET http://localhost:8000/exchanges/438d3c1a-a236-45ae-98ec-9e4f967fdd65
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MTc0ODMsImV4cCI6MTcyMjgyMTA4M30.z9skYX8OxHP-Rdi7gpbfVXlSLxeBoHB6R-kYINhpp-8

###

### GET exchanges/user/:anunciante_id
GET http://localhost:8000/exchanges/user/01b9370a-2aa7-4194-8e7a-a8a374b19288
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MTc0ODMsImV4cCI6MTcyMjgyMTA4M30.z9skYX8OxHP-Rdi7gpbfVXlSLxeBoHB6R-kYINhpp-8

###

### POST exchanges
POST http://localhost:8000/exchanges
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MTc0ODMsImV4cCI6MTcyMjgyMTA4M30.z9skYX8OxHP-Rdi7gpbfVXlSLxeBoHB6R-kYINhpp-8

{
    "titulo": "criando titulo de anuncio",
    "titulo_livro_oferecido": "livro oferecido",
    "autor_livro_oferecido": "autor do livro oferecido",
    "genero_livro_oferecido": "genero do livro oferecido",
    "titulo_livro_solicitado": "titulo do livro que quero",
    "autor_livro_solicitado": "autor do livro que quero",
    "genero_livro_solicitado": "gereno do livro que quero",
    "descricao": "tanto faz",
    "anunciante_id": "01b9370a-2aa7-4194-8e7a-a8a374b19288"
}

###

### PUT exchanges/:id
PUT http://localhost:8000/exchanges/438d3c1a-a236-45ae-98ec-9e4f967fdd65
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MTc0ODMsImV4cCI6MTcyMjgyMTA4M30.z9skYX8OxHP-Rdi7gpbfVXlSLxeBoHB6R-kYINhpp-8

{
    "titulo": "atualizado criando titulo de anuncio",
    "titulo_livro_oferecido": "atualizado livro oferecido",
    "autor_livro_oferecido": "atualizado autor do livro oferecido",
    "genero_livro_oferecido": "genero do livro oferecido",
    "titulo_livro_solicitado": "titulo do livro que quero",
    "autor_livro_solicitado": "autor do livro que quero",
    "genero_livro_solicitado": "gereno do livro que quero",
    "descricao": "tanto faz",
    "anunciante_id": "01b9370a-2aa7-4194-8e7a-a8a374b19288"
}

###

### PATH exchanges/:id
PATCH  http://localhost:8000/exchanges/438d3c1a-a236-45ae-98ec-9e4f967fdd65
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MTc0ODMsImV4cCI6MTcyMjgyMTA4M30.z9skYX8OxHP-Rdi7gpbfVXlSLxeBoHB6R-kYINhpp-8

###

### DELETE exchanges/:id
DELETE  http://localhost:8000/exchanges/438d3c1a-a236-45ae-98ec-9e4f967fdd65
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI4MTc0ODMsImV4cCI6MTcyMjgyMTA4M30.z9skYX8OxHP-Rdi7gpbfVXlSLxeBoHB6R-kYINhpp-8

