### users.http
#### USERS

### allUsers
GET http://localhost:8000/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI3MTYwMDAsImV4cCI6MTcyMjcxOTYwMH0.DmdvKv-WipAVna9r3Uf7x4PeEZJ_d6Lj57mht4xHVEg

###

### byIdUser
GET http://localhost:8000/users/01b9370a-2aa7-4194-8e7a-a8a374b19288
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxYjkzNzBhLTJhYTctNDE5NC04ZTdhLWE4YTM3NGIxOTI4OCIsImVtYWlsIjoibWFyaWFAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjI3MTYwMDAsImV4cCI6MTcyMjcxOTYwMH0.DmdvKv-WipAVna9r3Uf7x4PeEZJ_d6Lj57mht4xHVEg

###

### createUser  1
POST http://localhost:8000/users
Content-Type: application/json

{
    "nome": "João da Silva",
    "email": "joao@example.com",
    "senha": "senha123",
    "enderecos": {
        "logradouro": "Rua Exemplo",
        "numero": "123",
        "bairro": "Centro",
        "complemento": "Apto 45",
        "cep": "12345678",
        "municipio": "Cidade Exemplo",
        "uf": "EX"
    },
    "telefones": [
        {
            "contato": "999999999"
        }
    ]
}


###

### Create User 2
POST http://localhost:8000/users
Content-Type: application/json

{
    "nome": "Maria Oliveira",
    "email": "maria@example.com",
    "senha": "senha1234",
    "enderecos": {
        "logradouro": "Avenida Principal",
        "numero": "456",
        "bairro": "Bairro Novo",
        "complemento": "",
        "cep": "87654321",
        "municipio": "Outra Cidade",
        "uf": "OC"
    },
    "telefones": [
        {
            "contato": "888888888"
        }
    ]
}


###

### updateUser
PUT http://localhost:8000/users/90cfefd0-6854-4ad0-8faa-3b1c29b41a17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwY2ZlZmQwLTY4NTQtNGFkMC04ZmFhLTNiMWMyOWI0MWExNyIsImVtYWlsIjoiam9hb0BleGFtcGxlLmNvbSIsImlhdCI6MTcyMjcxNDc2MiwiZXhwIjoxNzIyNzE4MzYyfQ.1TOt4K8-liy_pPc-hWqOxIod-dypWq_Q4QXs20gJ44Q
Content-Type: application/json

{
    "nome": "João da Silva Novo",
    "email": "joao@example.com",
    "senha": "senha123",
    "enderecos": {
        "logradouro": "Rua Exemplo novo",
        "numero": "123",
        "bairro": "Centro novo",
        "complemento": "Apto 45",
        "cep": "12345678",
        "municipio": "Cidade Exemplo novo",
        "uf": "EX"
    },
    "telefones": [
        {
            "contato": "2222222"
        }
    ]
}


###


### deleteUser
DELETE http://localhost:8000/users/90cfefd0-6854-4ad0-8faa-3b1c29b41a17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwY2ZlZmQwLTY4NTQtNGFkMC04ZmFhLTNiMWMyOWI0MWExNyIsImVtYWlsIjoiam9hb0BleGFtcGxlLmNvbSIsImlhdCI6MTcyMjcxNDc2MiwiZXhwIjoxNzIyNzE4MzYyfQ.1TOt4K8-liy_pPc-hWqOxIod-dypWq_Q4QXs20gJ44Q




###



### login
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "maria@example.com",
    "senha": "senha1234"
}

###


### userProfile
GET http://localhost:8000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwY2ZlZmQwLTY4NTQtNGFkMC04ZmFhLTNiMWMyOWI0MWExNyIsImVtYWlsIjoiam9hb0BleGFtcGxlLmNvbSIsImlhdCI6MTcyMjcxMTcyMCwiZXhwIjoxNzIyNzE1MzIwfQ.D_IitVpxk7wLKSUIMlZSw_7aTzIKU4_vgt47ltac6FA




